# Generated by Django 4.2.3 on 2023-07-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width')),
                ('title1', models.CharField(blank=True, max_length=200, null=True)),
                ('desc1', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width')),
                ('title2', models.CharField(blank=True, max_length=200, null=True)),
                ('desc2', models.TextField(blank=True, null=True)),
                ('image2', models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width')),
                ('title3', models.CharField(blank=True, max_length=200, null=True)),
                ('desc3', models.TextField(blank=True, null=True)),
                ('image3', models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services_heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('heading', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('heading', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
